resilience4j:
  retry:
    instance:
      atm-controller:
        maxRetryAttemtps: 5
        waitDuration: 1s
        exponentialBackOff: true
      default:
        limit-for-period: 3
        limit-refresh-period: 10s
spring:
  application:
    name: xerocry-atm-service
server:
  port: ${port:8300}
#  ssl:
#    key-store: classpath:keystore/springboot.p12
#    key-store-password: password
#    key-store-type: pkcs12
#    key-alias: springboot
#    key-password: password

bankServiceUrl: https://localhost:8100/api/v1/
